# Generated by Django 5.2.10 on 2026-01-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('photoUrl', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('langID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissionID', models.AutoField(primary_key=True, serialize=False)),
                ('codeName', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('colorCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('authorID', models.ForeignKey(db_column='authorID', on_delete=django.db.models.deletion.CASCADE, to='store.author')),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('isThumbnail', models.BooleanField(default=False)),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('parentID', models.ForeignKey(blank=True, db_column='parentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cityID', models.ForeignKey(db_column='cityID', on_delete=django.db.models.deletion.CASCADE, to='store.city')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('imgID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('reviewID', models.ForeignKey(db_column='reviewID', on_delete=django.db.models.deletion.CASCADE, to='store.review')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('tagID', models.ForeignKey(db_column='tagID', on_delete=django.db.models.deletion.CASCADE, to='store.tag')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('profileID', models.AutoField(primary_key=True, serialize=False)),
                ('employeeCode', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notiID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('profileID', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(max_length=255)),
                ('loyaltyPoints', models.IntegerField()),
                ('dob', models.DateField()),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('parentID', models.ForeignKey(blank=True, db_column='parentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.comment')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('isDefault', models.BooleanField(default=False)),
                ('cityID', models.ForeignKey(db_column='cityID', on_delete=django.db.models.deletion.CASCADE, to='store.city')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignedDate', models.DateTimeField()),
                ('roleID', models.ForeignKey(db_column='roleID', on_delete=django.db.models.deletion.CASCADE, to='store.role')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField()),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('wishlistID', models.ForeignKey(db_column='wishlistID', on_delete=django.db.models.deletion.CASCADE, to='store.wishlist')),
            ],
        ),
    ]
