# Generated by Django 5.2.10 on 2026-01-31 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('statusID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('taxCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartID', models.AutoField(primary_key=True, serialize=False)),
                ('sessionKey', models.CharField(max_length=255)),
                ('updatedAt', models.DateTimeField()),
                ('userID', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('cartID', models.ForeignKey(db_column='cartID', on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
            ],
        ),
        migrations.CreateModel(
            name='ImportSlip',
            fields=[
                ('slipID', models.AutoField(primary_key=True, serialize=False)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('staffID', models.ForeignKey(db_column='staffID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
                ('supplierID', models.ForeignKey(db_column='supplierID', on_delete=django.db.models.deletion.CASCADE, to='store.supplier')),
                ('warehouseID', models.ForeignKey(db_column='warehouseID', on_delete=django.db.models.deletion.CASCADE, to='store.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('slipID', models.ForeignKey(db_column='slipID', on_delete=django.db.models.deletion.CASCADE, to='store.importslip')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shippingFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('detailID', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('orderID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('historyID', models.AutoField(primary_key=True, serialize=False)),
                ('changedAt', models.DateTimeField()),
                ('changedBy', models.ForeignKey(db_column='changedBy', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
                ('orderID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('statusID', models.ForeignKey(db_column='statusID', on_delete=django.db.models.deletion.CASCADE, to='store.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('returnID', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('refundAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orderID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('entryID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('warehouseID', models.ForeignKey(db_column='warehouseID', on_delete=django.db.models.deletion.CASCADE, to='store.warehouse')),
            ],
        ),
    ]
