# Generated by Django 5.2.10 on 2026-01-31 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orderstatus_supplier_warehouse_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bannerID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(max_length=255)),
                ('linkUrl', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaignID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('carrierID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('apiKey', models.CharField(max_length=255)),
                ('hotline', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discountID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=50)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('methodID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('configJSON', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecModel',
            fields=[
                ('modelID', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('lastTrained', models.DateTimeField()),
                ('algorithm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('configID', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponID', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('usageLimit', models.IntegerField()),
                ('discountID', models.ForeignKey(db_column='discountID', on_delete=django.db.models.deletion.CASCADE, to='store.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('orderID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='RecResult',
            fields=[
                ('resultID', models.AutoField(primary_key=True, serialize=False)),
                ('bookListJSON', models.TextField()),
                ('score', models.FloatField()),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('trackingCode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('orderID', models.ForeignKey(db_column='orderID', on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('rateID', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=100)),
                ('minWeight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrierID', models.ForeignKey(db_column='carrierID', on_delete=django.db.models.deletion.CASCADE, to='store.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingTrace',
            fields=[
                ('traceID', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('shipmentID', models.ForeignKey(db_column='shipmentID', on_delete=django.db.models.deletion.CASCADE, to='store.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transID', models.AutoField(primary_key=True, serialize=False)),
                ('gatewayRef', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('paymentID', models.ForeignKey(db_column='paymentID', on_delete=django.db.models.deletion.CASCADE, to='store.payment')),
            ],
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actionType', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('bookID', models.ForeignKey(db_column='bookID', on_delete=django.db.models.deletion.CASCADE, to='store.book')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isUsed', models.BooleanField(default=False)),
                ('couponID', models.ForeignKey(db_column='couponID', on_delete=django.db.models.deletion.CASCADE, to='store.coupon')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
    ]
