# Generated by Django 5.2.10 on 2026-01-31 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner_campaign_carrier_discount_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categoryID',
            field=models.ForeignKey(blank=True, db_column='categoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
    ]
