# Generated by Django 5.2.10 on 2026-01-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='importslip',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
