# Generated by Django 5.2.10 on 2026-01-31 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_importslip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cityID',
        ),
        migrations.AddField(
            model_name='address',
            name='districtID',
            field=models.ForeignKey(db_column='districtID', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.district'),
        ),
    ]
